# throw()
- throw让开发人员抛出一个自定义的异常信息
- throw代码执行后，程序会中断到catch块，如果没有catch则程序终止执行
```
console.log('错误1'); // 错误1
throw("aaa"); // 错误信息对象.html:6 Uncaught aaa
console.log('错误2'); // 该语句没有被执行
```
# error对象
```
// 一般浏览器
var mistake = new Error("我是错误信息");
throw mistake;  // Uncaught Error: 我是错误信息
```
```
//IE and edge
var mistake2 = new Error(50,"我是错误信息") 
throw mistake2 ;    
```
```
var mistake = new Error();
mistake.message = "我是错误信息";
mistake.name = "错误名字";
throw mistake;
```